[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/create-payment"
  to = "/.netlify/functions/create-payment"
  status = 200

[[redirects]]
  from = "/api/check-payment"
  to = "/.netlify/functions/check-payment"
  status = 200
